@Korp.Billing.Api_HostAddress = https://localhost:7066

### Create Invoice
POST {{Korp.Billing.Api_HostAddress}}/api/invoices
Content-Type: application/json

{
  "items": [
    {
      "productId": "c93e275e-423f-4c41-91c1-eb92b983a9bb",
      "quantity": 999
    }
  ]
}

### Get All Invoices
GET {{Korp.Billing.Api_HostAddress}}/api/invoices
Accept: application/json

### Get Invoice By Id
GET {{Korp.Billing.Api_HostAddress}}/api/invoices/566f4638-8945-467e-889e-61587418a818
Accept: application/json

### Print Invoice
POST {{Korp.Billing.Api_HostAddress}}/api/invoices/566f4638-8945-467e-889e-61587418a818/print